### ISSUE TITLE
Erro na instalação via pip no Debian 6

### ISSUE THREAD

**Issue by maisonsakamoto** [vkruoso/receita-tools#14]
estou usando debian6 quando executo o comando 

> pip install receita-tools

> error: command 'i586-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-2LEOCI/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-20p39S-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2LEOCI/cffi

**Comment by vkruoso** [comment]
Vou investigar qual pode ser o problema. Por hora, pode verificar se instalar o pacote ``python-cffi`` e resolve?

**Comment by maisonsakamoto** [comment]
instalei o `python-cffi` mas não resolveu :(

**Comment by vkruoso** [comment]
@maisonsakamoto As vezes o pip em si gera alguns problemas nesses casos. Dependendo das versões que estão instaladas pode ser que o resultado seja diferente.

Pode tentar o seguinte:

```
$ sudo apt-get install build-essential libssl-dev libffi-dev python-dev
```
(da [documentação](https://cryptography.io/en/latest/installation/) do módulo cryptography)

E então:
```
$ pip install -U cffi
$ pip install -U receita-tools
```

Aguardo seu feedback para fecharmos o issue.

**Comment by maisonsakamoto** [comment]
Bom dia, vou testar agora

**Comment by maisonsakamoto** [comment]
agora funcionou!

**Comment by vkruoso** [comment]
Ótimo! Qualquer probleba durante o uso da ferramenta por favor nos avise!
