### ISSUE TITLE
Erro 'CNPJ rejeitado pela Receita Federal' para empresa existente

### ISSUE THREAD

**Issue by VanderleiDenir** [vkruoso/receita-tools#20]
A API está retornando o erro 'CNPJ rejeitado pela Receita Federal' para as empresas ativas.

Os CNPJs base para correção são: 
09.226.381/0001-04
04.863.442/0001-12

**Comment by vkruoso** [comment]
Refiz as consultas dos CNPJs citados acima e ambos estão retornando corretamente agora. Vou manter este issue aberto para realizarmos a implementação de uma verificação que irá evitar que esse problema aconteça para CNPJs já existentes em nossa base.

**Comment by VanderleiDenir** [comment]
Casos anteriores estão coretos.

Segue nova lista com a mesma situação:
11809003000197
10220108000224
09001879001213
04517075000103
09553743000163
05693968000164
06080096000121
03639257000186
83758391000135
22679153000140
07824162000193
01720723000128
03588270000153
12085457000125
03501604000100
13589165000192
12249646000196
01495139000116

**Comment by vkruoso** [comment]
Acho que não está claro como tratamos CNPJs Rejeitados pela Receita. Na página de preços (https://www.receitaws.com.br/pricing) temos apenas uma nota e na página de FAQ (https://www.receitaws.com.br/faq) um parágrafo indicando esta limitação. O que acham que poderíamos fazer para melhorar neste ponto?

De qualquer forma, removi nossa base de CNPJs rejeitados nos últimos 90 dias (191.013 CNPJs) então todas as novas requisições serão tratadas novamente. Fiz uma re-consulta com os 22 CNPJs deste issue e do issue #22 e todos estes CNPJs devem estar corretos agora.

Novamente vou manter o issue aberto de acordo com o comentário anterior.

**Comment by rhuanbarreto** [comment]
Segue mais uma lista de rejeitados:
01.182.204/0002-34
86.700.390/0001-28
04.463.276/0019-96
03.052.564/0008-32
25.526.428/0001-01
96.513.486/0005-64
25.058.001/0001-18
24.122.924/0001-29
64.948.656/0001-13
26.292.303/0001-19
23.119.588/0001-00
21.339.965/0020-46
92.753.268/0001-12
46.100.426/0001-18
03.324.310/0001-50
11.149.881/0002-04
22.572.616/0001-70
13.526.884/0001-64
10.722.866/0001-60
24.185.522/0004-16
22.940.725/0001-00
23.150.886/0001-55
33.182.809/0074-96
21.783.963/0001-89
21.808.713/0001-56
11.801.379/0001-55
26.416.041/0001-57
01.542.714/0004-37
23.469.656/0001-53
24.399.002/0001-63
24.345.616/0001-62
26.210.561/0001-09
03.584.647/0007-91
24.281.509/0001-18
15.752.002/0001-04
08.506.545/0001-86
26.622.435/0001-61
26.391.097/0001-02
07.498.009/0004-66
26.043.053/0001-83
26.153.473/0001-12
28.152.650/0083-18
00.903.166/0004-60
08.470.309/0002-38
16.492.411/0002-62
02.693.750/0056-95
07.480.811/0007-71
80.378.052/0004-88
19.486.258/0001-78
58.034.315/0005-63
29.884.632/0008-13
33.112.152/0036-65
33.112.152/0028-55
21.303.715/0001-93
03.948.423/0001-26
17.712.475/0001-03
26.387.277/0001-02
15.691.731/0001-06
62.545.686/0016-30
04.192.552/0002-80
03.138.061/0003-70
21.203.157/0001-94
32.319.931/0038-35
18.597.384/0001-37
04.070.135/0001-84
24.750.649/0001-98
21.961.168/0001-33
77.679.686/0001-13
15.702.040/0001-52
02.430.739/0001-69
19.659.983/0001-09
18.599.044/0001-45
39.692.108/0001-28
24.117.690/0001-21
16.957.047/0001-88
21.069.291/0001-44
78.559.440/0005-02
33.112.152/0037-46
61.150.751/0037-90
18.416.738/0001-08
05.904.868/0003-00

**Comment by VanderleiDenir** [comment]
Segue mais uma lista de rejeitados:
63456560000175
53154225000320
05371069000145

**Comment by vkruoso** [comment]
Correções no sistema devem evitar que isso aconteça novamente. Peço que reabra o issue caso detecte alguma situação assim.

**Comment by Rufino89** [comment]
Olá,

Estou com problema na API comercial onde alguns CNPJs não estão trazendo dados da RF (não é erro ou CNPJ rejeitado, apenas a informação da situação cadastral e outras vêm em branco.

Segue amostra:

01666158000168
29466828000111
09244130000144
09610495000145
69607059000149
18300210000160
08929261000100
19713230000126
05484328000144
14946789000182

Todos consultados no endereço abaixo e estão com situação ativa.

http://www.receita.fazenda.gov.br/PessoaJuridica/CNPJ/cnpjreva/Cnpjreva_Solicitacao.asp

Fico no aguardo.

**Comment by chavesmarcos** [comment]
42.782.198/0001-52

Consultado no endereço abaixo e consta com situação ativa.

http://www.receita.fazenda.gov.br/PessoaJuridica/CNPJ/cnpjreva/Cnpjreva_Solicitacao.asp

Fico no aguardo.
