### ISSUE TITLE
Erro de consulta para empresa com mais de 20 atividades secundarias

### ISSUE THREAD

**Issue by VanderleiDenir** [vkruoso/receita-tools#21]
Verificar empresas com mais de 20 atividades secundarias, onde o resultado é paginado pela receita federal.
Os CNPJs base para correção são:  
09.226.381/0001-04

**Comment by vkruoso** [comment]
Acabei de fazer esta consulta e o CNPJ indicado possui 16 atividades, ficando em uma página apenas. Nós tratamos este caso de várias páginas, veja um exemplo: 00.817.788/0001-23. Você possui algum outro exemplo em que essa situação está ocorrendo?

**Comment by vkruoso** [comment]
Fechando por inatividade. Caso encontre um caso em que as atividades secundárias não estão sendo retornadas corretamente, por favor, reabrir este issue.
