### ISSUE TITLE
CNPJ Correto devolvendo status de recusado pela receita federal

### ISSUE THREAD

**Issue by rhuanbarreto** [vkruoso/receita-tools#22]
Estou recebendo o erro de 'CNPJ rejeitado pela Receita Federal' para o CNPJ 01.482.825/0001-52 que existe normalmente.

**Comment by rhuanbarreto** [comment]
60.541.240/0001-25 Também

**Comment by VanderleiDenir** [comment]
Erro já reportado na issue #20.

**Comment by vkruoso** [comment]
Fechando este issue já que ele foi resolvido no issue #20. Obrigado pelo report @rhuanbarreto.
