### ISSUE TITLE
Informações em branco

### ISSUE THREAD

**Issue by VanderleiDenir** [vkruoso/receita-tools#27]
CNPJ Base: 04.878.675/0001-99

Os seguintes campos estão diferentes do site oficial:
  "cep": "",
  "bairro": "",
  "municipio": "",
  "uf": "",
  "email": "",
  "telefone": "",
  "situacao": "",
  "data_situacao": "",
  "capital_social": "0.00",
  "qsa": [],

![image](https://user-images.githubusercontent.com/5240835/41073844-8d7834e6-69db-11e8-996a-e4a6fa401e82.png)
![image](https://user-images.githubusercontent.com/5240835/41073872-a4573b4e-69db-11e8-9040-ebb548732739.png)

Sendo atualização de dados, pelo menos a situação não deveria estar preenchida? Existe empresa com situação não definida?

PS: O campo 'Porte' presente no site também não consta na API, seria uma informação nova?

**Comment by vkruoso** [comment]
Este CNPJ já foi atualizado. Estamos adicionando mecanismos para que isso não aconteça no futuro.
