### ISSUE TITLE
Retornar QSA / Capital Social

### ISSUE THREAD

**Issue by tiagocardosos** [vkruoso/receita-tools#4]
@vkruoso quando consultamos no site da receita, ele cria um botão na parte inferior da tela "Consulta QSA / Capital Social".

Ele submete o arquivo "Cnpjreva_qsa.asp", mas, tem que usar o mesmo session da consulta do CNPJ.

Seria possível adicionar ao serviço?

Tela de exemplo:
<img width="681" alt="screen shot 2015-07-29 at 11 04 31" src="https://cloud.githubusercontent.com/assets/1429801/9027228/b0356ee0-3923-11e5-87a3-c96a460a27bd.png">

**Comment by alcampagnani** [comment]
Principal item que falta no WS para ficar perfeito!

**Comment by vkruoso** [comment]
@tiagocardosos @alcampagnani Estou fazendo esta implementação agora, porém preciso de um CNPJ com um QSA mais completo. Vejo que no quadro retornado existem alguns campos extras, como "Representante Legal" e "País de Origem". Estou buscando um CNPJ que tenha estas informações, porém se alguém tiver um exemplo agiliza o processo.

**Comment by tiagocardosos** [comment]
@vkruoso utiliza esse cara 30.306.294/0001-45

**Comment by vkruoso** [comment]
Verifiquei aqui e este CNPJ não apresenta estes outros campos.

**Comment by rhuanbarreto** [comment]
@vkruoso 02.333.707/0001-45
<img width="1291" alt="captura de tela 2016-10-19 as 13 39 29" src="https://cloud.githubusercontent.com/assets/283004/19525954/7df38548-9601-11e6-86fa-8a47b5d01dfd.png">

**Comment by vkruoso** [comment]
@rhuanbarreto Obrigado. Exatamente o que precisamos para cobrir todos os casos. Assim que tivermos novidades informo aqui.

**Comment by vkruoso** [comment]
@tiagocardosos @alcampagnani @rhuanbarreto 

Está no ar há cerca de uma semana esta melhoria em nossos coletores de dados. Já estamos com grande parte do banco de dados atualizado. Um exemplo seria https://www.receitaws.com.br/v1/cnpj/27865757000102 .

A descrição da API também foi atualizada para descrever melhor os campos retornados. 
https://www.receitaws.com.br/api

Caso precise destes dados antes de toda a atualização da base, é possível utilizar a API Comercial. Maiores detalhes podem ser obtidos nos links abaixo.
https://www.receitaws.com.br/faq
https://www.receitaws.com.br/pricing
