### ISSUE TITLE
Retornar situação da empresa com relação ao FGTS

### ISSUE THREAD

**Issue by vkruoso** [vkruoso/receita-tools#6]
Isso inclui o status com relação ao FGTS e a descrição do status.

**Comment by vkruoso** [comment]
Fechando por hora visto que não temos grande interesse nesta feature.

**Comment by rhuanbarreto** [comment]
Isso é possível? É como se baixasse a certidão de regularidade do FGTS?

**Comment by vkruoso** [comment]
Exato. Existe o serviço abaixo que lhe permite fazer essa verificação.
http://www.fgts.gov.br/empregador/servicos_online/consulta_crf.asp
