### ISSUE TITLE
Inconsistência com a consulta no site da receita

### ISSUE THREAD

**Issue by douglasmk** [vkruoso/receita-tools#7]
Consultando uma série de CNPJ's verifiquei que alguns dados retornados pelo receitaws.com.br são bem diferentes do retornado pela consulta no site da receita (http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/Cnpjreva_Solicitacao2.asp)

**Comment by vkruoso** [comment]
Já observamos este comportamento com alguns CNPJs porém não conseguimos encontrar a fonte do problema por ele ocorrer com alguns CNPJs isolados. Poderia dizer quais CNPJs foram consultados e estão inconsistentes?

**Comment by douglasmk** [comment]
Aí estão alguns:
```
11061673000178
11065644000184
11155151000135
11176232000111
12670241000127
```
você usa uma base de dados paralela ou consulta diretamente o ws da receita?

**Comment by vkruoso** [comment]
A suspeita ainda é a mesma, e a correção está sendo testada. Acabei encontrando mais 107 CNPJs que tem exatamente a mesma informação que alguns passados. Se tiver verificado outros CNPJs retornando dados estranhos, peço que liste-os aqui para que eu possa verificar se outros também não foram afetados.

**Comment by vkruoso** [comment]
Estou fechando esse issue visto que aqueles CNPJs indicados foram corrigidos e já está no ar a correção que melhora as requisições para evitar caches. A qualquer momento que verificar um CNPJ com dados incorretos, favor indicá-los aqui neste issue e reabri-lo.

**Comment by douglasmk** [comment]
Encontrei mais alguns

```
12670855000109
12683135000188
13406264000191
13406485000160
14783078000134
14803616000105
15398667000161
15401991000191
```
percebi que em algumas consultas, o valor retornado é sempre repetido.

**Comment by vkruoso** [comment]
Vou reabrir para verificar esses casos. Agora que a correção está no ar, aos poucos estes CNPJs devem se corrigir automaticamente, mas vou procurar os duplicados destes CNPJs para corrigí-los também.

Isso pode ser o efeito de um proxy muito ruim, que estava retornando os mesmos dados para vários CNPJs diferentes. Se a solução atual se mostrar pouco efetiva em evitar esse tipo de problema, podemos implementar algum outro mecanismo para evitá-lo.

**Comment by vkruoso** [comment]
Foram mais 535 CNPJs corrigidos. Vou fazer uma verificação geral em breve para procurar mais duplicados. Por isso vou manter o issue aberto. Se tiver mais CNPJs pode enviar aqui.

**Comment by vkruoso** [comment]
A última atualização é que há alguns dias realizei uma atualização de vários (50k +-) CNPJs que tinham suspeita de dados duplicados. Estou monitorando novos CNPJs e atualizações para diagnosticar se o problema vai volta a ocorrer ou não. Por hora deve estar tudo ok. Vou fechar o issue apenas quando tive um processo automático de verificação.

**Comment by vkruoso** [comment]
A verificação automática ficará para outra versão. Por hora não tivemos nenhum sinal de dados incorretos. Se acontecer novamente, por favor abrir este issue novamente.

**Comment by RodrigoSantos** [comment]
Boa tarde ! Encontrei este CNPJ 79132833000166 na Receita e no Sintegra está PR e aqui está uma informação nada ver em SP.

**Comment by RodrigoSantos** [comment]
Teste ok, obrigado.

**Comment by vkruoso** [comment]
Não tivemos outros reports relacionados aos dados da API. Estamos criando processos para melhorar a confiabilidade dos dados.

**Comment by RodrigoSantos** [comment]
Boa tarde ! Problema voltou a acontecer com este CNPJ 68542521000104.

**Comment by vkruoso** [comment]
Reabrindo.

**Comment by vkruoso** [comment]
As medidas tomadas parecem ter surtido efeito visto que há meses não temos informações sobre problemas com os dados. Por hora, fechando.
