### ISSUE TITLE
Retornar "Regime de Tributação" e "Contribuinte ICMS"

### ISSUE THREAD

**Issue by fernandohlaranjo** [vkruoso/receita-tools#8]
Haveria a possibilidade de incluir as informações sobre o "**Regime de Tributação**"(Simples Nacional, Lucro Presumido, Lucro Real) e "**Contribuinte ICMS**"(sim/não) caso tenham acesso à fonte das mesmas?

Obrigado!

**Comment by maisonsakamoto** [comment]
eu estou fazendo a consulta do Regima de Tributação através do projeto https://github.com/nfephp-org/nfephp tem um exemplo ali 4.00testaCadastro.php, poderia este projeto tentar incorporar alguma ideia dali, só que não sei se será possível porque aqui o desenv. é py e lá é php, por hora estou usando ambos porque o receita-tools só precisa passar o cnpj como parametro, já o nfephp precisa passar a UF também.

**Comment by vkruoso** [comment]
Ao implementar o suporte aos novos dados vamos verificar o projeto indicado, que parece bastante interessante. Não posso dizer se será possível aproveitar o projeto como está, mas com certeza será de grande ajuda.

**Comment by vkruoso** [comment]
Por hora fechando este issue. Não vamos ter banda para tratar esta atualização no momento. Caso alguém tenha interesse em colaborar podemos pensar em como atingir este objetivo.
